name: Build
on:
  push:
    tags:
    - '*'

jobs:
  ocamlformat-dockerfile:
    name: ocamlformat binaries via docker
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest]
        ocaml: ["5.2.1", "5.1.1"]
        include:
          - os: ubuntu-latest
            version: "0.26.2"
            ocaml: "5.2.1"
            target_triple: x86_64-unknown-linux-musl
          - os: ubuntu-latest
            version: "0.26.1"
            ocaml: "5.1.1"
            target_triple: x86_64-unknown-linux-musl

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Build ocamlformat
        run: |
          docker buildx build build-scripts/ocamlformat --target=export --output type=local,dest=$(pwd)/out/ --build-arg TAG=${{ github.ref_name }} --build-arg TARGET=${{ matrix.target_triple }} --build-arg OCAML_VERSION=${{ matrix.ocaml }} --build-arg OCAMLFORMAT_VERSION=${{ matrix.version }}
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "out/*.tar.gz"
